### ISSUE TITLE
Page 69 Typo

### ISSUE THREAD

**Issue by mattolde** [angular-tips/deep-angular-issues#1]
Hi Jesús,

Enjoying your book so far. Just found a typo on page 69.

ng-stransclude should be ng-transclude

![screen shot 2015-04-28 at 5 10 29 pm](https://cloud.githubusercontent.com/assets/599655/7364409/8bbfc100-edc9-11e4-8914-e531e11533a9.png)

**Comment by Foxandxss** [comment]
Thanks, fixed it.
